"""2B-4: dominio financiero 3 tablas

Revision ID: 4fc03133254b
Revises: d2d33b5e6a0f
Create Date: 2026-04-08 15:48:12.301000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fc03133254b'
down_revision: Union[str, None] = 'd2d33b5e6a0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commission_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('commission_base', sa.Enum('purchase_price', 'sale_price', name='commissionbase'), nullable=True),
    sa.Column('min_shipment_amount_for_free_shipping', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('active_from', sa.DateTime(), nullable=False),
    sa.Column('active_to', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tax_name', sa.String(length=100), nullable=False),
    sa.Column('tax_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('applies_from', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commission_periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('gross_sales_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('commission_base_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('shipping_charges', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_commission', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'paid', name='commissionperiodstatus'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commission_periods')
    op.drop_table('tax_settings')
    op.drop_table('commission_settings')
    # ### end Alembic commands ###
