"""campos de devolucion parcial en order_items

Revision ID: 9d7cdfbf93a9
Revises: 4dc3c0a11827
Create Date: 2026-04-16 22:26:48.134821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d7cdfbf93a9'
down_revision: Union[str, None] = '4dc3c0a11827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('returned_quantity', sa.Integer(), nullable=True))
    op.add_column('order_items', sa.Column('return_reason', sa.String(length=50), nullable=True))
    op.add_column('order_items', sa.Column('returned_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_status_history', 'changed_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('order_items', 'returned_at')
    op.drop_column('order_items', 'return_reason')
    op.drop_column('order_items', 'returned_quantity')
    # ### end Alembic commands ###
