"""2B-extra: campo tags en products

Revision ID: d2d33b5e6a0f
Revises: bf86cf0c13a2
Create Date: 2026-04-08 15:44:30.061119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2d33b5e6a0f'
down_revision: Union[str, None] = 'bf86cf0c13a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'tags')
    # ### end Alembic commands ###
